# -*- coding: utf-8 -*-
"""arrayoperation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mFnzyfpGWKz4ANAgqCi_T0TsjIhsqPh6
"""

import numpy as np
array_from_list=np.array([1,2,3,4,5])
print("Array from list:",array_from_list)

array_with_range=np.arange(10)
print("array with range:",array_with_range)

zeros_array=np.zeros((3,3))
print("array of zeros:\n",zeros_array)

ones_array=np.ones((2,5))
print("array of ones:\n",ones_array)

a=np.array([1,2,3])
b=np.array([4,5,6])

add_result=np.add(a,b)
print("Additio:",add_result)

sub_result=np.subtract(a,b)
print("subtraction:",sub_result)

mul_result=np.multiply(a,b)
print("multiplication:",mul_result)

div_result=np.divide(a,b)
print("divion:",div_result)

array=np.arange(12)
print("original array:",array)