# -*- coding: utf-8 -*-
"""bubble

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10CLf5dnXLx5ow-Osay6nVJ8_66EQlO62
"""

import matplotlib.pyplot as plt
x=[1,2,3,4,5]
y=[10,15,13,8,7]
sizes=[100,200,300,400,500]
plt.scatter(x,y,s=sizes, alpha=0.5,c='blue')
plt.xlabel('x-axis')
plt.ylabel('y-axis')
plt.title('bubble chart example')
plt.show()

import matplotlib.pyplot as plt
x=[1,2,3,4,5]
y=[10,15,13,8,7]
sizes=[100,200,300,400,500]
colors=[20,30,40,50,60]
plt.scatter(x,y,s=sizes,c=colors,alpha=0.6,cmap='viridis')
plt.colorbar(label='color scale')
plt.xlabel('x-axis label')
plt.ylabel('y-axis label')
plt.title('bubble chart with color dimension')
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.linspace(0,10,100)
y1=np.sin(x)
y2=np.cos(x)
fig,axs=plt.subplots(2,1,figsize=(8,8))

axs[0].plot(x,y1,'b')
axs[0].set_title('sine function')
axs[0].set_ylabel('sin(x)')
axs[1].plot(x,y2,'r')
axs[1].set_title('cosine function')
axs[1].set_ylabel('cos(x)')
axs[1].set_xlabel('x')
plt.tight_layout()
plt.show()

