# -*- coding: utf-8 -*-
"""prm10

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v7N5NCdSMXsCzLS0Rlf4Mht_SkEQOnOY
"""

import numpy as np
import pandas as pd
data={'Name':['Tom','nick','krish','jack'],'Age':[20,21,19,18]}
df=pd.DataFrame(data)
print(df)

data={'Name':['Jai','principal','Gaurav','Anu'],
      'Age':[27,24,22,32],
      'Adress':['Delhi','Kanpur','Allahabad','Kannuj'],
      'Qualification':['Msc','MA','MCA','phd']}
df=pd.DataFrame(data)
print(df[['Name','Qualification']])

import pandas as pd
data=pd.read_csv("/content/emp1.csv")
data.info()

data.head()

first=data.head()
print(first)

import pandas as pd
import numpy as np
arr=np.array([10,15,18,22])
s=pd.Series(arr)
print(s)

arr=np.array(['a','b','c','d'])
s=pd.Series(arr, index=['first','second','third','fourth'])
print(s)

s=pd.Series(50, index=[0, 1, 2, 3, 4])
print (s)

d={'Name': 'Deepthi', 'Class' : 'MCA', 'year' : 2014}
s=pd.Series(d)
print(s)

s = pd.Series([10,15,18,22])
df=pd.DataFrame(s)
df.columns=['List1']
df['List2']=20
df['List3']=df['List1']+df['List2']
print(df)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
np.random.seed(0)
values = np.random.randn(100)
s = pd.Series(values)
print("series\n",s)
s.plot(kind='hist', title='Normally distributed random values')
plt.show()

df = pd.DataFrame({'A': [1, 2, 1, 4, 3],
'B': [12, 14, 11, 16, 18],
'C': ['a', 'a', 'b', 'a', 'b']})
df

import pandas
iris = pandas.read_csv('/content/iris.csv')
print(iris)

import pandas as pd
iris = pd.read_csv('/content/iris.csv')
print(iris.head())

import pandas as pd
df = pd.DataFrame(pd.read_csv("/content/iris.csv"))
df.hist()

iris['sepalleng'].hist()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
data = pd.read_csv ('/content/room.csv')
data.describe()
data.head()

import seaborn as sns
import matplotlib.pyplot as plt
data = sns.load_dataset('tips')
sns.scatterplot(x='total_bill', y='tip', data=data)
plt.title('Scatter Plot of Total Bill vs. Tip')
plt.xlabel('Total Bill')
plt.ylabel('Tip')
plt.show()

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
data = pd.read_csv ('/content/room.csv')
plt.figure(figsize=(10, 8))
sns.scatterplot(x='husvalue', y='age',
data=data)
plt.title('Scatter Plot for Median House Value vs. Housing Median Age')
plt.xlabel('Median House Value')
plt.ylabel('Housing Median Age')
plt.show()

plt.figure(figsize=(15, 10))
sns.boxplot(x='age', y='husvalue', data=data)
plt.title('Box Plot for Feature1 by Target')
plt.show()