# -*- coding: utf-8 -*-
"""programs

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1giHNCmKvix8iRG0R9fPAgp1KIMjwu-Zz
"""

import numpy as np
matrix1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix_sum = matrix1 + matrix2
matrix_diff = matrix1 - matrix2
matrix_product = matrix1 * matrix2
matrix_divide = matrix1 / matrix2
matrix_multiply = np.dot(matrix1, matrix2)
matrix1_transpose = np.transpose(matrix1)
diagonal_sum = np.trace(matrix1)
print("Matrix 1:\n", matrix1)
print("Matrix 2:\n", matrix2)
print("Matrix Sum:\n", matrix_sum)
print("Matrix Difference:\n", matrix_diff)
print("Matrix Element-wise Product:\n", matrix_product)
print("Matrix Element-wise Division:\n", matrix_divide)
print("Matrix Multiplication:\n", matrix_multiply)
print("Transpose of Matrix 1:\n", matrix1_transpose)
print("Sum of Diagonal Elements of Matrix 1:", diagonal_sum)

import numpy as np

x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])
print("Matrix x is:\n", x)
print("Matrix y is:\n", y)
a = np.power(x, 2)
result = a + 2 * y
print("x^2 + 2*y is:\n", result)

import numpy as np
A=np.array([[2,1,-2],[3,0,1],[1,1,-1]])
b=np.array([-3,5,-2])
x = np.linalg.solve(A, b)
print("matrix A:")
print(A)
print("vector b:")
print(b)
print("solution for x:")
print(x)

